name: golf_stats_app
description: "골프 라운드 데이터 분석 프로토타입 웹 애플리케이션"
publish_to: 'none'
version: 1.1.0+1

environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.5.1
  json_annotation: ^4.9.0
  fl_chart: ^0.68.0
  intl: ^0.19.0
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.9
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
  assets:
    - assets/data/
