// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'shot.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

Shot _$ShotFromJson(Map<String, dynamic> json) => Shot(
  shotId: json['shot_id'] as String,
  holeScoreId: json['hole_score_id'] as String,
  userId: json['user_id'] as String,
  shotNumber: (json['shot_number'] as num).toInt(),
  clubType: json['club_type'] as String,
  shotType: json['shot_type'] as String,
  lie: json['lie'] as String,
  isPutt: json['is_putt'] as bool,
  puttMade: json['putt_made'] as bool?,
  puttLength: (json['putt_length'] as num?)?.toDouble(),
  isMulligan: json['is_mulligan'] as bool? ?? false,
  shotAt: json['shot_at'] as String?,
  totalDistance: (json['TOTAL'] as num?)?.toDouble(),
  carryDistance: (json['CARRY'] as num?)?.toDouble(),
  height: (json['HEIGHT'] as num?)?.toDouble(),
  landAngle: (json['LAND_ANG'] as num?)?.toDouble(),
  sideDeviation: (json['SIDE'] as num?)?.toDouble(),
  sideTotal: (json['SIDE_TOT'] as num?)?.toDouble(),
  hangTime: (json['HANG_TIME'] as num?)?.toDouble(),
  fromPin: (json['FROM_PIN'] as num?)?.toDouble(),
  ballSpeed: (json['BALL_SPEED'] as num?)?.toDouble(),
  launchAngle: (json['LAUNCH_ANG'] as num?)?.toDouble(),
  launchDirection: (json['LAUNCH_DIR'] as num?)?.toDouble(),
  spinRate: (json['SPIN_RATE'] as num?)?.toDouble(),
  spinAxis: (json['SPIN_AXIS'] as num?)?.toDouble(),
  backSpin: (json['BACK_SPIN'] as num?)?.toDouble(),
  sideSpin: (json['SIDE_SPIN'] as num?)?.toDouble(),
  smashFactor: (json['SMASH_FAC'] as num?)?.toDouble(),
  attackAngle: (json['ATTACK_ANG'] as num?)?.toDouble(),
  clubPath: (json['CLUB_PATH'] as num?)?.toDouble(),
  dynamicLoft: (json['DYN_LOFT'] as num?)?.toDouble(),
  spinLoft: (json['SPIN_LOFT'] as num?)?.toDouble(),
  faceAngle: (json['FACE_ANG'] as num?)?.toDouble(),
  faceToPath: (json['FACE_TO_PATH'] as num?)?.toDouble(),
  clubSpeed: (json['CLUB_SPEED'] as num?)?.toDouble(),
);

Map<String, dynamic> _$ShotToJson(Shot instance) => <String, dynamic>{
  'shot_id': instance.shotId,
  'hole_score_id': instance.holeScoreId,
  'user_id': instance.userId,
  'shot_number': instance.shotNumber,
  'club_type': instance.clubType,
  'shot_type': instance.shotType,
  'lie': instance.lie,
  'is_putt': instance.isPutt,
  'putt_made': instance.puttMade,
  'putt_length': instance.puttLength,
  'is_mulligan': instance.isMulligan,
  'shot_at': instance.shotAt,
  'TOTAL': instance.totalDistance,
  'CARRY': instance.carryDistance,
  'HEIGHT': instance.height,
  'LAND_ANG': instance.landAngle,
  'SIDE': instance.sideDeviation,
  'SIDE_TOT': instance.sideTotal,
  'HANG_TIME': instance.hangTime,
  'FROM_PIN': instance.fromPin,
  'BALL_SPEED': instance.ballSpeed,
  'LAUNCH_ANG': instance.launchAngle,
  'LAUNCH_DIR': instance.launchDirection,
  'SPIN_RATE': instance.spinRate,
  'SPIN_AXIS': instance.spinAxis,
  'BACK_SPIN': instance.backSpin,
  'SIDE_SPIN': instance.sideSpin,
  'SMASH_FAC': instance.smashFactor,
  'ATTACK_ANG': instance.attackAngle,
  'CLUB_PATH': instance.clubPath,
  'DYN_LOFT': instance.dynamicLoft,
  'SPIN_LOFT': instance.spinLoft,
  'FACE_ANG': instance.faceAngle,
  'FACE_TO_PATH': instance.faceToPath,
  'CLUB_SPEED': instance.clubSpeed,
};
